language: python
python:
    - "2.7"
    #- "2.6"
    #
virtualenv:
    - system_site_packages: true

before_install:
    - "sudo apt-get install -qq python-numpy python-scipy"
install:
    #- "pip install -r requirements.txt --use-mirrors"
    #- - "pip install numpy --use-mirrors"
    #- - "pip install scipy --use-mirrors"
    - "pip install nose-exclude --use-mirrors"

script: 
    - python -c 'import scipy'
    - nosetests
