language: python
python:
  - "2.7"
  #- "2.6"
  #
virtualenv:
  system_site_packages: true

before_install:
  - "sudo apt-get update -qq"
  - "sudo apt-get install -qq libgeos-3.2.2 libgeos-dev python-numpy python-scipy"

install:
  - "pip install -q -r requirements.txt --use-mirrors"
  - "pip install coveralls --use-mirrors"
  #- "pip install pysal --use-mirrors"
  #- "pip uninstall -y pysal"

script: 
  - python -c 'import numpy; print numpy.version.version'
  - python -c 'import scipy; print scipy.version.version'
  - python -c 'import pysal; print pysal.version'
  - nosetests 
  #- python setup.py sdist >/dev/null
  - cd doc; make pickle; make doctest
notifications:
    email:
        recipients:
            - sjsrey@gmail.com
            - pstephens@gmail.com
            - daniel.arribas.bel@gmail.com
            - dfolch@gmail.com
            - jlaura@gmail.com
            - drferling@gmail.com
            - lanselin@gmail.com
            - pedrovma@gmail.com
            - schmidtc@gmail.com
        on_success: always
        on_failure: always
