language: python
python:
  - "2.7"
  #- "2.6"
  #
virtualenv:
  system_site_packages: true

before_install:
  - "sudo apt-get update -qq"
  - "sudo apt-get install -qq libgeos-3.2.2 python-numpy python-scipy"

install:
  - "pip install -r requirements.txt --use-mirrors"
  - "pip install pysal --use-mirrors"
  - "pip uninstall -y pysal"

script: 
  - python -c 'import numpy; print numpy.version.version'
  - python -c 'import scipy; print scipy.version.version'
  - nosetests
  - python setup.py sdist >/dev/null
  - cd doc; make pickle; make doctest
