language: python

sudo: false

matrix:
  include:
    - env: ENV_FILE="ci/travis/36-latest-conda-forge.yaml"
    - env: ENV_FILE="ci/travis/37-latest-conda-forge.yaml"

install:
  # Install conda
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes --set changeps1 no
  - conda install conda=4.6
  - conda info

  # Install dependencies
  - conda env create --file="${ENV_FILE}"
  - source activate test
  - make download
  - make convert
  - pip install -e .
  - conda list

script:
  - python setup.py sdist >/dev/null
  - echo "check_stable=False" >libpysal/config.py
  - nosetests --with-doctest --verbose --with-coverage --cover-package=libpysal -I shapely_ext.py;
  #- cd doc; make pickle; make doctest
notifications:
    email:
        recipients:
            - sjsrey@gmail.com
            - levi.john.wolf@gmail.com
        on_success: change 
        on_failure: always

after_success:
  - coveralls
