language: python
sudo: false
branches:
only:
  - master
python:
  - "2.7"
  - "3.4"
  - "3.5"

env:
  - PYSAL_PLUS=false
  - PYSAL_PLUS=true

before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p ./miniconda
  - export PATH=`pwd`/miniconda/bin:$PATH
  - conda update --yes conda
  - conda create -y -q -n test-env python=$TRAVIS_PYTHON_VERSION
  - source activate test-env
  - if [[ $TRAVIS_PYTHON_VERSION == 3* ]]; then 2to3 -nw pysal/ > /dev/null; fi

install:
  - conda install --yes numpy scipy nose pip
  - if [ "$PYSAL_PLUS" == true ]; then
        echo 'plus testing'; conda install --yes pandas numexpr numba patsy shapely; fi;
  - pip install -r travis.txt

script: 
  - python -c 'import numpy; print(numpy.__version__)'
  - python -c 'import scipy; print(scipy.__version__)'
  - python setup.py install  >/dev/null
  - python -c 'import pysal'
  #- python -c 'import multiprocessing as mp; print mp.cpu_count()'
  #- pychecker --limit 1000 pysal
  - python setup.py sdist >/dev/null
  #- nosetests --processes=-1 --process-timeout=60 --verbosity=1 --ignore-files=collection --exclude-dir=pysal/contrib
  #- nosetests
  - echo "check_stable=False" >pysal/config.py
  - nosetests --with-coverage --cover-package=pysal; 
  #- cd doc; make pickle; make doctest
notifications:
    email:
        recipients:
            - sjsrey@gmail.com
            - levi.john.wolf@gmail.com
            - dfolch@gmail.com
            - daniel.arribas.bel@gmail.com
            - weikang9009@gmail.com
            - carsonfarmer@gmail.com
            - tayoshan@gmail.com
            - marynia.kolak@gmail.com
            - jgaboardi@gmail.com
            - phil.stphns@gmail.com
        on_success: always
        on_failure: always

after_success:
  - coveralls
