name: pysal
channels:
  - conda-forge
  - defaults
dependencies:
  - python >=3.6
  - libpysal>=4.3.5
  - access>=1.1.1
  - esda>=2.3.5
  - giddy>=2.3.3
  - inequality>=1.0.0
  - pointpats>=2.2.0
  - segregation>=1.5.0
  - spaghetti>=1.5.6
  - mgwr>=2.1.2
  - spglm>=1.0.8
  - spint>=1.0.7
  - spreg>=1.2.2
  - spvcm>=0.3.0
  - tobler>=0.5.4
  - mapclassify>=2.4.2
  - splot>=.1.1.3
  - spopt>=0.0.5
  - urllib3 >=1.26
