language: python
sudo: false
branches:
only:
  - master
python:
  - "3.5"
  - "3.6"

env:
  - PYSAL_PLUS=false
  - PYSAL_PLUS=true

before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p ./miniconda
  - export PATH=`pwd`/miniconda/bin:$PATH
  - conda update --yes conda
  - conda config --add channels conda-forge
  - conda create -y -q -n test-env python=$TRAVIS_PYTHON_VERSION
  - source activate test-env

install:
  - conda install --yes pip
  - pip install -r requirements.txt
  - pip install -r requirements_tests.txt

script:
  - python setup.py sdist >/dev/null
  - python setup.py install
  - nosetests --verbose --with-coverage --cover-package=mgwr

notifications:
    email:
        recipients:
            - tayoshan@gmail.com
        on_change: always
        on_failure: always

after_success:
  - coveralls
